### ISSUE TITLE
perform unit test for `File` and `FIleData` relationship

### ISSUE THREAD

**Issue by SirNoob97** [SirNoob97/storage-service#15]
Classes related:

- [File](https://github.com/SirNoob97/storage-service/blob/main/src/main/java/com/sirnoob97/storageservice/file/entity/File.java)
- [FileData](https://github.com/SirNoob97/storage-service/blob/main/src/main/java/com/sirnoob97/storageservice/file/entity/FileData.java)

**Comment by 9gl** [comment]
Hey @SirNoob97 ,
I'm interested in contributing to this issue, so before I start working it, would you mind sparing your time explaining what the issue is about and pointing me to some resources to get started.

**Comment by SirNoob97** [comment]
Hello @9gl and thanks for help, this issue deals all the test cases related to: 

- the persist operation (`save` method). ej. null data entity, null fields. etc. 

- the dele operations. ej. Delete a `FileData` record but no the related `File` owner. etc

If you can, try to solve the problems you find with sql or pl-sql pls. if not report a new issue.

**Comment by 9gl** [comment]
@SirNoob97 could you point me to the files and some resources to get started .

**Comment by SirNoob97** [comment]
Sorry.

Links in the issue descriptions are updated.

Pls use the gradle wrapper `gradlew`.

Run especific test method with this
./gradlew test --tests <teast class>.<test name>

**Comment by SirNoob97** [comment]
The resources im using are spring jpa docs, postgres docs and any stackoverflow family forum

**Comment by SirNoob97** [comment]
Hi @9gl do you still want to work on this?

**Comment by 9gl** [comment]
I am busy currently so won't be able to contribute sorry :)
